#Test cleaning the data
import pandas as pd
df = pd.read_csv("titanic.csv")
print(df)
print(df.head())
print(df.shape)
print(df.isnull().sum())
print(df.info())
df = df.drop("Cabin",axis=1)
print(df)
print(df.duplicated().sum())
print(df.isnull().sum())
df["Age"] = df["Age"].fillna(df["Age"].mean())
print(df)
df["Fare"] = df["Fare"].fillna(df["Fare"].mean())
print(df)
print(df.isnull().sum())
print(df["Pclass"].value_counts())
print(df.groupby("Survived")["Age"].mean())
print(df[(df["Age"] > 30) & (df["Survived"] == 1)])
df["AgeGroup"] = df["Age"].apply(lambda x: "Child" if x < 18 else "Adult")
print(df)   
